name: Tests

on:
  workflow_run:
    workflows: ["Restore"]
    types: [completed]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore payment-plataform.sln

      - name: Test with coverage
        run: dotnet test payment-plataform.sln --collect:"XPlat Code Coverage" --results-directory "coverage"

      - name: Upload raw coverage
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-raw
          path: coverage

      - name: Generate Report
        uses: danielpalme/ReportGenerator-GitHub-Action@5.3.7
        with:
          reports: coverage/**/coverage.cobertura.xml
          targetdir: coverage-report
          reporttypes: Html

      - name: Upload final report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage-report
